import * as styles from './PNGExport.module.css';

import { BoldSpan } from './BoldSpan';

import { CyanBoldSpan } from './CyanBoldSpan';

import { detectWindows, detectMac } from '@rnacanvas/utilities';

export class PNGExport {
  readonly domNode = document.createElement('p');

  readonly #PNG = CyanBoldSpan('PNG');

  readonly #keyBinding = (
    detectWindows() ? BoldSpan('Windows key+Shift+S')
    : detectMac() ? BoldSpan('Shift+Command+4')
    : undefined
  );

  constructor() {
    this.domNode.classList.add(styles['png-export']);

    let PNG = this.#PNG;

    let keyBinding = this.#keyBinding;

    if (keyBinding) {
      this.domNode.append(PNG, ' images can be generated by taking a screenshot (press ', keyBinding, ' and select the area to export).');
    } else {
      this.domNode.append(PNG, ' images can be generated by taking a screenshot.');
    }
  }
}
